### ISSUE TITLE
Code block is not rendered correctly

### ISSUE THREAD

**Issue by BirkhoffG** [srush/mamba-scans#1]
Hi @srush, thank you for your great blog. Unfortunately, the code block is not rendered correctly on my web browser:

![image](https://github.com/srush/mamba-scans/assets/26811230/15afbd80-840a-4da5-b2ab-6dc08d0851e2)

**Comment by srush** [comment]
Sorry this was just a temp repo..real version is here.

https://srush.github.io/annotated-mamba/hard.html

**Comment by BirkhoffG** [comment]
Thank you so much @srush
